== W życiu każdego z nas przychodzi taki moment...

[NOTE.speaker]
====
*KUBA*

* w karierze każdego z nas przychodzi taki moment
* zaczynamy czymś lub kimś zarządzać
** czasem czymś: produkt, stajemy się PO
** czasem kimś: dostajemy do opieki zespół
* mniej lub bardziej świadomie zaczynacie zarządzać
** z własnej inicjatywy lub nie
** stajemy przed taką życiową sytuacją
====

[%notitle, data-background-image=https://media.giphy.com/media/MqRtijz2xdEvS/giphy.gif, data-background-size=cover]
== Life hack

[NOTE.speaker]
====
W życiu każdego z nas przychodzi taki moment...
====


[data-background-image=https://media.giphy.com/media/MqRtijz2xdEvS/giphy.gif, data-background-size=cover]
== Life hack

[NOTE.speaker]
====
...że potrzebny jest jest lifehack
====


== Life hack

[NOTE.speaker]
====
* no więc postanowiliśmy podzielić się kilkoma life-hackami
* kilka tematów, tipów, spostrzeżeń które nam pomogły
** gdy przechodziliśmy ze ścieżki technicznej na miękką/managerską
** myślimy że te rzeczy są z jednej strony dość uniwersalne
** ale to nie jest coś co można przyjść i zaaplikować w swoim kontekście, to tak nie zadziała
** traktujemy to bardziej jako inspirację
** to nie są wzorce projektowe ani prawdy objawione
====

== To jest Bartek

*Programista Excela*

[NOTE.speaker]
====
* dużo gada
====


== To jest Kuba

*Architekt PowerPointa*

[NOTE.speaker]
====
*BARTEK*

* gada jeszcze więcej
* mam do Was małą prośbę - pytania na koniec, bo chcemy zachować spójność opowieści
** jak dojdą przerwania niemaskowane to będzie ciężej
* przechodzimy z krainy bytecodu do krainy outlooka i excela stoi przed nami wiele wyzwań
* kiedy one przede mną stały spytałem HRy o szkolenia dla swetra, który przechodzi na miękką ścieżkę
* wiecie ile ich było? ...
====

[%notitle, data-background-image=https://media.giphy.com/media/xTk9ZVv4GDWOx5fSVy/giphy.gif, data-background-size=cover]
== Ksiązki z HR

[NOTE.speaker]
====
* Było ich dokładnie 0
====


[%notitle, data-background-image=https://media.giphy.com/media/w48WeMIN73QsM/giphy.gif, data-background-size=cover]
== Czarna magia

[NOTE.speaker]
====
*KUBA*

* Nie mająć szkoleń, znalazłszy się w takiej sytuacji staramy sobie poradzić najlepiej jak umiemy
* To co próbujemy zrobić to trochę taka czarna magia, działamy na czuja, bez przygotowania, staramy się radzić z sytuacją, która nas zastała najlepiej jak potrafimy
* będziemy chcieli podzielić się kilkoma koncepcjami, które pomogły nam okiełznać tę czarną magię
* kilka zaklęć, które potrafią postawić świat w lepszym świetle, *powinno być łatwiej*
* *To nie jest tylko* prezetnacja dla osób, które dopiero zaczynają
* Wydaje nam się, że osoby, które zarządzają dłuższy czas też znajdą coś przydatnego dla siebie
* Znowu, w życiu każdego z nas jest taki moment...
====

[%notitle, data-background-image=https://media.giphy.com/media/l39713bIWEWDoNMzK/giphy.gif, data-background-size=cover]
== Koń po Pardubickiej

[NOTE.speaker]
====
*KUBA*

* ...że wracamy z pracy i czujemy się jak koń po wielkiej pardubickiej, albo jeszcze gorzej jak jego dżokej
* mamy za sobą cały dzień pracy pełen bezsensowych zadań, czasem 10h, czasem Warszawskie 8 czyli od 8 do 8
* poza tym, że odpowiedzieliśmy na masę maili to mamy wrażenie, że tego dnia nic sensownego się nie wydarzyło i nic nie osiągneliśmy
** co gorsza to wrażenie dotatkowo pogarsza fakt, że zespół, z którym pracujemy coraz bardziej nam odjeżdża
*** że implicte types Twojego zespołu coraz bardziej rozjeżdzają się z Twomi tabelami przestawnymi
**** ja wiem, że excel jest reactive, ale to nie to samo cool
*** że twój master jest coraz bardziej w tyle za developem
** A na koniec dobija Ciebie fakt, iż mimo dużego bagażu doświadczeń co chwilę coś idzie inaczej niż zaplanowałeś/coś Ciebie zaskakuje.
** Jedyne co ma się siłe to kanapa, lampka..., szklanka..., a czasami butelka czerwonego wina i jeżeli mamy siły to książka
====


[%notitle, data-background-image=https://media.giphy.com/media/1MTLxzwvOnvmE/giphy.gif, data-background-size=cover]
== Ale kim my jesteśmy

[NOTE.speaker]
====
*BARTEK*

* Dlaczego ktoś m przyjść posłuchać dwóch Minionków?
* Żeby nie było za bardzo subiektywnie do naszych doświadczeń znaleźliśmy predykaty z literatury fachowej.
* Nie ma też co się zachłysnąć zaweaulowalną literaturą i badaniami amerykańskich naukowców.
** Papier przyjmie wszystko, często przedstawia najprostrze przykłady i pomija porażki.
** Prawdziwa nauka odbywa się na placu boju.
====
