== Historia pierwsza

_Przepraszam, czy tu biją?_

[NOTE.speaker]
====
* mamy dla Was 4 historie
* opowieści z naszego doświadczenia, z którymi mamy nadzieję, łatwo będzie się utorzsamić
* każdą z historii zaczynamy cytatem ze wspomnianej literatury fachowej
* historia pierwsza
====


[%notitle]
== Don't be a Scrum Mom

[quote]
____
Przełożony musi dać odczuć swą obecność pracownikowi, który szuka, +
a skryć się przed tym, który znalazł.
____

[NOTE.speaker]
====
* *Przełożony musi dać odczuć swą obecność pracownikowi, który szuka, +
a skryć się przed tym, który znalazł.*

{zwsp}

* i odnieśmy teraz ten cytat do naszej codziennej pracy
====


[%notitle, data-background-image=https://memegenerator.net/img/instances/500x/59694709/i-had-a-scrum-once-it-was-awful.jpg, data-background-size=cover]
== Tried SCRUM and it was awful

[NOTE.speaker]
====
* często przygoda z zarządzaniem zaczyna się od pytania: ogarnąłbyś dzisiaj daily?
* Spokojnie, my też robiliśmy SCRUMa, było okropnie
** od tego zaczniemy - chociaż nie będziemy mówić tylko o Scrumie
* Wykazaliśmy się przy organizacji pierwszego daily, także pada nastepne pytanie: czy nie chciałbyś zacząć organizować daily?
* a my nie chcemy przestać kodować
** chcemy organizować to daily z doskoku, bo wiadomo, że programiści mają najfajniejsze zabawki
** jeżeli ktoś się z tym nie zgadza to wierzę, że na pewno ma jakieś inne zalety
* I to traktowanie organizacji daily z doskoku to błąd, bo wchodzimy na inne terytorium
* SCRUM Master ma swoje poziomy rozwoju (development levels)
====

[%notitle, data-background-image=images/developing-scrum-masters-39-728.jpg, data-background-size=contain, data-background="#fff", data-background-repeat=no-repeat]
== Steps towards maturity

[NOTE.speaker]
====
* Scrum Master - jak wszystko ma swoje maturity model

// .Stages of becoming a leader
* Od czegoś trzeba zacząć i jest to zazwyczaj odpytka na daily
** wczoraj, dzisiaj, czy coś przeszkadza im w osiągnięciu celu sprintu
** odpytka jest mechaniczna, z tyłu głowy kompilujemy i przerywa nam to pracę
* Szybko się orientujemy, że to odpytka to nie jest to co chcielibyśmy robić.
* Odkrywamy, że nie różni się to dużo od mikrozarządzania, nie mamy na to czasu. Wiemy / czujemy że to nie tak
** To co chcielibyśmy robić to pomóc zespołowi, rozwiązać ich jakieś problemy, usunąć ich jakieś przeszkody
** *nie po to studiowałeś 5 lat infomatykę aby teraz robić za sekretarkę*, prawda?
* bardzo szybko chcemy odejść od pierwszego stadium. `The Scrum Dude/Scrum Guy`
** stajemy przed straszną sytuacją, bo połowa zespołu nas nienawidzi, a połowa nam współczuje....nie wiemy która połowa jest która.
* chcemy awansować na kolejny poziom czyli `Scrumowa Mamusia`
** nie rób tego, rób to, nie wchodz na krzesło, nie wchodz na stół, bo spadniesz. *`Mamusia` pozmywa* x2
* Szybko się orientujemy, że to droga do nikąd, my mamy coraz więcej pracy, coraz mniej kodujemy, a zespół jest coraz bardziej dziecinny
** chcieliśmy dobrze, a wyszło jak zawsze
* nie chcemy być arogandzkim typkiem zza biurka `Pointy-haired Boss`
* ktoś coś powiedział o liderze... tylko jak zacząć? *mieć szacunek, zaufnie. Ale jak?*
* Posłużmy się przykładem - skąd brać informacje o projekcie i obecnym stanie rzeczy w inny sposób?
** nie ma większego antywzorca niż PM, który totalnie nie ogarnia postępu projektu i przesuwa sobie codziennie suwaczek postępu o 1/128 w excelku
** co robi początkujący lider, który napotka problem? organizuje spotkanie
*** ale jest to jeden z gorzszych sposobów na dowiedzenie się jak idzie w projekcie
*** na szczęście tych sposobów jest więcej
====

[%notitle, data-background-image=images/methods-to-find-out-whats-going-on-415x557.png, data-background-size=contain, data-background-repeat=no-repeat, data-background="#EAE8DF"]
== Let's take meeting as an example

[NOTE.speaker]
====
* *Valve handbook for new employees*
** Lider musi znaleźć sposoby aby wiedzieć *implicite*
*** nie odpytuje, rozmawia z ludzmi, wie co się dzieje, czuje co się w projekcie dzieje
** tutaj nie ma już niestety miejsca na "bycie _on the top of pyramid_"
====

== Z pozycji siły nic nie wskóram

_Spotkanie statusowe nie jest miejscem gdzie wywierasz wpływ_

[NOTE.speaker]
====
// * Im szybciej to stanie się jasne, tym lepiej
* ludzie nie lubią autoratywnych managerów
** ludzie wolą kogoś z kim można porozmawiać niż `gnoja zza biurka`
** jak nas nie lubią to od nas odejdą za 500pln więcej do innej firmy
*** to oni mają po swojej stronie nadpopyt na rynku pracy, a my wtedy problem
* a jeżeli spotkanie statusowe nie ma być miejscem gdzie wywierasz wpływ, to wtedy gdzie i jak?
* możemy wpływać na ludzi jak nam ufają, jak mają do nas szacunek
** nie wystarczy, że postanowimy, że zaczniemy zbierać dane w sposób implicite, bo zespoł w cale nie musi chcieć z nami gadać
** Nie zrobimy tego poprzez tabelki i przezentacje
** żeby zespoł mi zaufał musi czuć, że ja chcę dla nich coś dobrego i chcę o nich zadbać
*** może trzeba się o nich zatroszczyć? `WAT?`
====


== cebulowy model szczęścia, cebula dobrostanu
_prof. Janusz Czapiński, 1989_

[NOTE.speaker]
====
* polski psycholog społeczny prof. Janusz Czapiński prowadził badania nad poziomem poczucia szczęścia (ogólny dobrostan subiektywny)
* można z niej wyciągnąć wniosek, że ludzie mają pewien poziom kiedy są zadowoleni z poszczególnych ich dziedzin życia, w tym zawodowej, ale też dziedzin prywatnych itp
* nasze zadanie jako liderów, wychodząc poza standardową rolę scrum mamusi, polega na tym, że musimy rozumieć co ich w życiu prywatnym boli, co ich boli w pracy i zaadresować te problemy
** jak będziemy robić to efektywnie to ludzie zobaczą, że nam zależy, że mogą nam zaufać
* i jest to pierwszy krok do tego żeby odejsć od spotkań statusowych, a zacząć zdobywać wiedzę w inny sposób
** i to jest podstawowe zadanie lidera
** a to jest ciężka codzienna praca
* i jak to można w praktyce zrobić?
====


[data-background-image=images/trust_me_engineer.png, data-background-size=cover]
== Trust me! I'm engineer

[NOTE.speaker]
====
* jeżeli zarządzacie jakimś projektem lub zespołem to wcześniej czy później pewne rzeczy rozbijają się o kasę, wszystko zawsze rozbija się o kasę
** *a nic tak nie pokazuje zaufania jak kwestia kasy*
* jeżeli z każdym wydatkiem musicie iść do przełożonego i prosić o akceptację niezależnie od jego kwoty to jest to sygnał, że ktoś komuś nie ufa
* co mi do tego jako liderowi, że ktoś chce kupić klawiaturę, albo książkę z amazona za 300pln
** jeżeli on uważa, że jest to dobrze wydana kasa to prawdopodobnie tak jest
** a zastanawiając się nad tym to 300pln np. co miesiąc w budżecie zespołu programistycznego to kropla w morzu
** to jest pierwszy punkt, w którym możemy pokazać, że zaufanie idzie w obie strony
** i w zespole Kuby po ustaleniu progu wydatku, którego nie trzeba u niego akceptować nie miał problemów, że ludzie kupowali świerszczyki, tylko rzeczywiście książki, których potrzebowali
* jeżeli powiecie, że w waszej organizacji nie możecie wprowadzić takiej zmiany, to inną okazją do tego są urlopy
** po co chodzić z akceptacją wniosków urlopowych?
** nie lepiej powiedzieć: słuchaj, to Ty wiesz najlepiej czy możesz iśc na urlop?
*** jeżeli sytuacja na to pozwala, to co mi do tego czy Ty chcesz iść na urlop
*** nie jestem Twoją mamusią, jesteś odpowiedzialnym człowiekiem
*** a jeżeli nie możesz, a chciałbyś wziąć urlop, to porozmawiajmy co trzeba zrobić żebyś mógł go wziąć
* działa tutaj zasada wzajemności
====

// ==  Służenie innym to priorytet numer jeden
//
// _The Servant Leader Manifesto &copy;_
//
// [NOTE.speaker]
// --
// * Zawsze chciałem mieć własne _manifesto_ może od tego zacznę?
// ** Chociaż naprawdę to pomysł Roberta Greenleafa
// * Czy inni wzrastają, tj:
// ** become healthier, wiser, freer, more autonomous, more likely themselves to become servants
// * Jeżeli myślimy że mamy władzę - to jej nie mamy
// ** Ci ludzie wiedzą że w ciągu 15 minut znajdą pracę.
// ** Mogą zachowywać się inaczej w naszej obecności - niż gdy nas nie ma
// * Nie ma miejsca na dyskusję, szacunek, zaufanie
// --

[%notitle, data-background-image=https://media.giphy.com/media/xWlPqPbrlkEQU/giphy.gif, data-background-size=cover]
== No dobra... ale co jeżeli...

[NOTE.speaker]
====
* Co zatem zrobić aby całość się nie rozłaziła?
** Jeżeli my nie kontrolujemy to skąd wiemy że będzie dobrze?
* Poluzujemy zespołowi - to co wtedy robi zespół.. skąd wiemy że robi dobrze
* *ze zmierza w dobrym kierunku a nie jest to samopas*
====
